### PR TITLE
Fixed the first parameter of substations

### PR DESCRIPTION
**Pull request by chqiao**
Fixed the first parameter of substations, which should be an integer (i.e., 0.0 -> 0).

### CODE REVIEW

**Comment by ghost** [comment]
Dear Qiao Cheng, many thanks for your correction. Unfortunately, the tutorial you refer is under revision: this 1-character “pull request” cannot be considered at the moment. Let me suggest you to notice me when you begin to work on a particular task related to SPHERA: this is not mandatory, but you would be granted to be the only person working on that topic and your associated pull requests would have priority. I apologize for the inconvenience. Many thanks again for your message. Have a nice day. Andrea

**Comment by chqiao** [comment]
Dear Andrea,
Since the 0.0 represents a real number, it caused an error when I performed the calculation. So I checked the input parameters and fixed the issue by the way. I understand your explanation, thank you for your reminder.
Have a nice day.
Qiao Cheng

**Comment by ghost** [comment]
Many thanks Qiao Cheng, 
your correction ("0" instead of "0.") for tutorial on the Vajont was appreciated. This tutorial did not belong to the release SPHERA v.9.0.0 and was only tested with the ifort compiler, which bypassed the error. In any case that input line does not influence the output. You are right, the executable produced with the gfortran compiler prevent the execution. Feel free to propose again this correction at a later stage, as suggested in the previous comment. 
Have a nice day
Andrea

**Comment by chqiao** [comment]
Dear Andrea,
I only tested the Vajont example under ubuntu with gfortran, and I am very happy to do something helpful for SPHERA. I will try to propose the correction of this issue again at the right time, thank you.
Have a nice day.
Qiao Cheng

**Pull request closed without merging**
